using System.Security.Cryptography.Pkcs;

namespace DigimonAndTamerCharacterSheets.Models;

internal class DigimonInfo
{
    public string DigimonName { get; set; } = null!;
    public string DigimonField { get; set; } = null!;
    public string DigitalFrame { get; set; } = null!;
    public int HPLevelMod { get; set; } = 0!;
    public string CoreHPMax { get; set; } = null!;
    public string MoveSpeed { get; set; } = null!;
    public string Attribute { get; set; } = null!;
    public string WeaknessElement { get; set; } = null!;
    public string ResistanceElement { get; set; } = null!;
    public bool FreshEvolution { get; set; } = false!;
    public bool TrainingEvolution { get; set; } = false!;
    public bool RookieEvolution { get; set; } = false!;
    public bool ChampionEvolution { get; set; } = false!;
    public bool UltimateEvolution { get; set; } = false!;
    public bool MegaEvolution { get; set; } = false!;
    public bool DarkEvolution { get; set; } = false!;
    public string CurrentQuirkOne { get; set; } = null!;
    public string CurrentQuirkTwo { get; set; } = null!;
    public string InheritableQuirkOne { get; set; } = null!;
    public string InheritableQuirkTwo { get; set; } = null!;
    public string InheritableQuirkThree { get; set; } = null!;
    public string BasicAttack { get; set; } = null!;
    public string StandardAttack { get; set; } = null!;
    public string SpecialAttack { get; set; } = null!;
    public string SuperAttack { get; set; } = null!;
    public string BasicDiceMin { get; set; } = null!;
    public string BasicDiceMax { get; set; } = null!;
    public string StandardDiceMin { get; set; } = null!;
    public string StandardDiceMax { get; set; } = null!;
    public string SpecialDiceMin { get; set; } = null!;
    public string SpecialDiceMax { get; set; } = null!;
    public string SuperDiceMin { get; set; } = null!;
    public string SuperDiceMax { get; set; } = null!;
    public string BasicElement { get; set; } = null!;
    public string StandardElement { get; set; } = null!;
    public string SpecialElement { get; set; } = null!;
    public string SuperElement { get; set; } = null!;
    public string BasicConcept { get; set; } = null!;
    public string BasicAttackStat { get; set; } = null!;
    public string BasicDefendStat { get; set; } = null!;
    public string BasicCritFail { get; set; } = null!;
    public string BasicCritSuccess { get; set; } = null!;
    public string BasicEffect { get; set; } = null!;
    public string BasicBonus { get; set; } = null!;
    public string BasicPenalty { get; set; } = null!;
    public string StandardConcept { get; set; } = null!;
    public string StandardAttackStat { get; set; } = null!;
    public string StandardDefendStat { get; set; } = null!;
    public string StandardCritSuccess { get; set; } = null!;
    public string StandardCritFail { get; set; } = null!;
    public string StandardEffect { get; set; } = null!;
    public string StandardBonus { get; set; } = null!;
    public string StandardPenalty { get; set; } = null!;
    public string SpecialConcept { get; set; } = null!;
    public string SpecialAttackStat { get; set; } = null!;
    public string SpecialDefendStat { get; set; } = null!;
    public string SpecialCritSuccess { get; set; } = null!;
    public string SpecialCritFail { get; set; } = null!;
    public string SpecialEffect { get; set; } = null!;
    public string SpecialBonus { get; set; } = null!;
    public string SpecialPenalty { get; set; } = null!;
    public string SuperConcept { get; set; } = null!;
    public string SuperAttackStat { get; set; } = null!;
    public string SuperDefendStat { get; set; } = null!;
    public string SuperCritSuccess { get; set; } = null!;
    public string SuperCritFail { get; set; } = null!;
    public string SuperEffect { get; set; } = null!;
    public string SuperBonus { get; set; } = null!;
    public string SuperPenalty { get; set; } = null!;
}
